CREATE USER IF NOT EXISTS 'tailjet'@'%' IDENTIFIED BY 'tailjet';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER ON `tailjet`.* TO 'tailjet'@'%';
GRANT REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'tailjet'@'%';
FLUSH PRIVILEGES;
