apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tailjet
  labels:
    app.kubernetes.io/name: tailjet
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tailjet
