apiVersion: v1
kind: Secret
metadata:
  name: tailjet
type: Opaque
stringData:
  TAILJET_MYSQL_PASSWORD: replace-me
  # Use one NATS authentication method:
  TAILJET_NATS_TOKEN: replace-me
  # TAILJET_NATS_CREDS: /var/run/secrets/nats/client.creds
  # TAILJET_NATS_USER: tailjet
  # TAILJET_NATS_PASSWORD: replace-me
